"""Bundle local JSON data into JS files for GitHub Pages (map-only deployment).

Source JSON files stay local (gitignored). Run after export_criteria_web.py.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
ASSETS = DOCS / "assets"


def compact_json(obj) -> str:
    return json.dumps(obj, separators=(",", ":"), ensure_ascii=False)


def bundle_district() -> None:
    criteria_dir = DOCS / "data" / "criteria"
    manifest_path = criteria_dir / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"Missing {manifest_path}")

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    months: dict[str, dict] = {}

    for path in sorted(criteria_dir.glob("values_*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        months[payload["date"]] = payload

    bundle = {"manifest": manifest, "months": months}
    out = ASSETS / "district-data.js"
    out.write_text(
        "/* Generated by scripts/bundle_web_data.py — do not edit */\n"
        f"window.__DISTRICT_MAP_BUNDLE__={compact_json(bundle)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {out.name} ({len(months)} months, {out.stat().st_size // 1024} KB)")


def bundle_grid() -> None:
    data_dir = DOCS / "data"
    manifest_path = data_dir / "manifest.json"
    if not manifest_path.is_file():
        print("No grid manifest — skipping grid-data.js")
        return

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    months: dict[str, dict] = {}

    for path in sorted(data_dir.glob("pm25_*.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        date_iso = payload.get("date")
        if not date_iso:
            m = re.search(r"pm25_(\d{4})_(\d{2})\.json", path.name)
            if m:
                date_iso = f"{m.group(1)}-{m.group(2)}-01"
        if date_iso:
            months[date_iso] = payload

    bundle = {"manifest": manifest, "months": months}
    out = ASSETS / "grid-data.js"
    out.write_text(
        "/* Generated by scripts/bundle_web_data.py — do not edit */\n"
        f"window.__GRID_MAP_BUNDLE__={compact_json(bundle)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {out.name} ({len(months)} months, {out.stat().st_size // 1024} KB)")


def main() -> None:
    ASSETS.mkdir(parents=True, exist_ok=True)
    bundle_district()
    bundle_grid()


if __name__ == "__main__":
    main()
